##==============================================================================
## Two's Complement
##
## @description: Makefile for twoscomplement.cc
## @author: Elisha Lai
## @version: 1.0 24/09/2015
##==============================================================================
NAME = "twoscomplement"

all:
	@echo "Compiling..."
	g++ -o $(NAME) $(NAME).cc

run: all
	@echo "Running..."
	./$(NAME) 

clean:
	rm $(NAME)
